added committee plugin config

diff --git a/templates/sc-p2p-entrypoint.sh.j2 b/templates/sc-p2p-entrypoint.sh.j2
--- a/templates/sc-p2p-entrypoint.sh.j2
+++ b/templates/sc-p2p-entrypoint.sh.j2
@@ -4,20 +4,8 @@ if [[ -f "/data/server.lock" ]]; then
 fi
 
 if [[ -f "/data/recovery.lock" ]]; then
-    echo "unable to recover. resetting chain..."
-    echo "backing up nemesis block"
-    mv /data/00000/00001.dat /data/00000/hashes.dat /tmp
-    echo "deleting data directory"
-    for dir in /data/*; do
-        rm -rf $dir
-    done
-    mkdir /data/00000
-    mv /tmp/00001.dat /tmp/hashes.dat /data/00000/
-    if [ ! -f "/data/index.dat" ]; then
-		echo "No index.dat file, creating now...."
-		echo -ne "\01\0\0\0\0\0\0\0" > /data/index.dat
-    fi
-    echo "data has been reset to nemesis block"
+    echo "unable to recover."
+    exit 1
 fi
 
 {{ sirius_binary_path }}/sirius.bc /chainconfig
